version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/code
    env_file:
      - backend/.env
    environment:
      - KNN_MIN_SCORE=${KNN_MIN_SCORE-0.94}
      - IS_EMBEDDING=${IS_EMBEDDING-true}
      - GCP_LOG_METRICS_ENABLED=${GCP_LOG_METRICS_ENABLED-False}
      - UPDATE_GRAPH_CHUNKS_PROCESSED=${UPDATE_GRAPH_CHUNKS_PROCESSED-20}
      - ENTITY_EMBEDDING=${ENTITY_EMBEDDING-False}
      - GCS_FILE_CACHE=${GCS_FILE_CACHE-False}
      - LLM_MODEL_CONFIG_OPENAI_GPT_4O=${LLM_MODEL_CONFIG_OPENAI_GPT_4O}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DIFFBOT_API_KEY=${DIFFBOT_API_KEY}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - MAX_TOKEN_CHUNK_SIZE=${MAX_TOKEN_CHUNK_SIZE}
    container_name: backend-dev
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8000:8000"
    networks:
      - net

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    container_name: frontend-dev
    ports:
      - "8080:8080"
    networks:
      - net

networks:
  net:
