FROM python:3.12-slim
WORKDIR /code
ENV PORT 8000
EXPOSE 8000

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libmagic1 \
    libgl1 \
    libglib2.0-0 \
    libglx-mesa0 \
    libgomp1 \
    libreoffice \
    cmake \
    poppler-utils \
    tesseract-ocr \
    git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH

COPY requirements.txt constraints.txt /code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt -c constraints.txt

COPY . /code

CMD ["uvicorn", "score:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
